map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen 80;
  server_name api.appzihub.fun auth.appzihub.fun app.appzihub.fun fifa.appzihub.fun;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name api.appzihub.fun;
  resolver 127.0.0.11 ipv6=off valid=30s;

  ssl_certificate /etc/letsencrypt/live/fifa.appzihub.fun/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/fifa.appzihub.fun/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    set $fifa_api http://fifa-api:8080;
    proxy_pass $fifa_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}

server {
  listen 443 ssl http2;
  server_name auth.appzihub.fun;
  resolver 127.0.0.11 ipv6=off valid=30s;

  ssl_certificate /etc/letsencrypt/live/fifa.appzihub.fun/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/fifa.appzihub.fun/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    set $fifa_identity_api http://fifa-identity-api:8080;
    proxy_pass $fifa_identity_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen 443 ssl http2;
  server_name app.appzihub.fun fifa.appzihub.fun;

  ssl_certificate /etc/letsencrypt/live/fifa.appzihub.fun/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/fifa.appzihub.fun/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
